[Interface]
# Key for mcp-docker
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 2JYUM+JeEXKQCSnaAhUCXqMAN3F6J5xQVZL2MDMTuEY=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# NL-FREE#280
PublicKey = Xn2BL+vhIggl2uJgoGccj0n0Cvw7OaeNK1wOfOutISQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 89.105.214.196:51820

PersistentKeepalive = 25